<a href="https://colab.research.google.com/github/harishkumar77/harishkumar77.github.io/blob/main/Deep_learning_DA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Preprocessing of training data**

In [ ]:
train = pd.read_csv('/content/furnace_train_set.txt', sep=';', header = None)
train.columns = ['time','energy','nitrogen_Nm3h']

In [ ]:
train

       date_column time_column  energy  nitrogen_Nm3h
0       2022-09-01    00:00:00     0.0            0.0
1       2022-09-01    00:00:15     0.0            0.0
2       2022-09-01    00:00:30     0.0            0.0
3       2022-09-01    00:00:45     0.0            0.0
4       2022-09-01    00:01:00     0.0            0.0
...            ...         ...     ...            ...
625509  2022-12-29    23:58:45     0.0            0.0
625510  2022-12-29    23:59:00     0.0            0.0
625511  2022-12-29    23:59:15     0.0            0.0
625512  2022-12-29    23:59:30     0.0            0.0
625513  2022-12-29    23:59:45     0.0            0.0

[625514 rows x 4 columns]

In [ ]:
train.isna().sum() #number of missing values in the training dataset(which means the placer is off at that time)

time                  0
energy            90235
nitrogen_Nm3h    325786
dtype: int64

In [ ]:
for energy in train:
    train[energy].fillna(0, inplace=True)

In [ ]:
train.isna().sum()

time             0
energy           0
nitrogen_Nm3h    0
dtype: int64

In [ ]:
train.head()

                        time  energy  nitrogen_Nm3h
0  2022-09-01 00:00:00+00:00     0.0            0.0
1  2022-09-01 00:00:15+00:00     0.0            0.0
2  2022-09-01 00:00:30+00:00     0.0            0.0
3  2022-09-01 00:00:45+00:00     0.0            0.0
4  2022-09-01 00:01:00+00:00     0.0            0.0

In [ ]:
import pandas as pd

# convert 'datetime_column' to pandas datetime object
train['time'] = pd.to_datetime(train['time'])

# extract date and time components into separate columns
train['date_column'] = train['time'].dt.date
train['time_column'] = train['time'].dt.time

print(train)

                            time  energy  nitrogen_Nm3h date_column  \
0      2022-09-01 00:00:00+00:00     0.0            0.0  2022-09-01
1      2022-09-01 00:00:15+00:00     0.0            0.0  2022-09-01
2      2022-09-01 00:00:30+00:00     0.0            0.0  2022-09-01
3      2022-09-01 00:00:45+00:00     0.0            0.0  2022-09-01
4      2022-09-01 00:01:00+00:00     0.0            0.0  2022-09-01
...                          ...     ...            ...         ...
625509 2022-12-29 23:58:45+00:00     0.0            0.0  2022-12-29
625510 2022-12-29 23:59:00+00:00     0.0            0.0  2022-12-29
625511 2022-12-29 23:59:15+00:00     0.0            0.0  2022-12-29
625512 2022-12-29 23:59:30+00:00     0.0            0.0  2022-12-29
625513 2022-12-29 23:59:45+00:00     0.0            0.0  2022-12-29

       time_column
0         00:00:00
1         00:00:15
2         00:00:30
3         00:00:45
4         00:01:00
...            ...
625509    23:58:45
625510    23:59:00
625511    23:59:15
625512    23:59:30
625513    23:59:45

[625514 rows x 5 columns]

In [ ]:
train.head()

                       time  energy  nitrogen_Nm3h date_column time_column
0 2022-09-01 00:00:00+00:00     0.0            0.0  2022-09-01    00:00:00
1 2022-09-01 00:00:15+00:00     0.0            0.0  2022-09-01    00:00:15
2 2022-09-01 00:00:30+00:00     0.0            0.0  2022-09-01    00:00:30
3 2022-09-01 00:00:45+00:00     0.0            0.0  2022-09-01    00:00:45
4 2022-09-01 00:01:00+00:00     0.0            0.0  2022-09-01    00:01:00

In [ ]:
train = train.drop('time', axis=1)

In [ ]:
train.head()

   energy  nitrogen_Nm3h date_column time_column
0     0.0            0.0  2022-09-01    00:00:00
1     0.0            0.0  2022-09-01    00:00:15
2     0.0            0.0  2022-09-01    00:00:30
3     0.0            0.0  2022-09-01    00:00:45
4     0.0            0.0  2022-09-01    00:01:00

In [ ]:
# select the columns in the order that you want them to appear
train = train[['date_column','time_column','energy', 'nitrogen_Nm3h']]

In [ ]:
train.head()

  date_column time_column  energy  nitrogen_Nm3h
0  2022-09-01    00:00:00     0.0            0.0
1  2022-09-01    00:00:15     0.0            0.0
2  2022-09-01    00:00:30     0.0            0.0
3  2022-09-01    00:00:45     0.0            0.0
4  2022-09-01    00:01:00     0.0            0.0

**Now let's do for the test data**

In [ ]:
test = pd.read_csv('/content/furnace_validation_set.txt', sep=';', header = None)
test.columns = ['time','energy','nitrogen_Nm3h']

In [ ]:
test.head()

                        time      energy  nitrogen_Nm3h
0  2022-10-11 19:50:30+00:00   9019.3995      19.440000
1  2022-10-11 19:50:45+00:00   6296.4840      19.428333
2  2022-10-11 19:51:00+00:00  15479.6640      19.585000
3  2022-10-11 19:51:15+00:00  11585.6500      20.127692
4  2022-10-11 19:51:30+00:00   6701.3010      19.685000

In [ ]:
import pandas as pd

# convert 'datetime_column' to pandas datetime object
test['time'] = pd.to_datetime(test['time'])

# extract date and time components into separate columns
test['date_column'] = test['time'].dt.date
test['time_column'] = test['time'].dt.time

In [ ]:
test = test.drop('time', axis=1)

In [ ]:
test = test[['date_column','time_column','energy', 'nitrogen_Nm3h']]

In [ ]:
test.head()

  date_column time_column      energy  nitrogen_Nm3h
0  2022-10-11    19:50:30   9019.3995      19.440000
1  2022-10-11    19:50:45   6296.4840      19.428333
2  2022-10-11    19:51:00  15479.6640      19.585000
3  2022-10-11    19:51:15  11585.6500      20.127692
4  2022-10-11    19:51:30   6701.3010      19.685000

**Implementation of model**

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

model1 = Sequential()
model1.add(InputLayer((5, 1)))
model1.add(LSTM(64))
model1.add(Dense(8, 'relu'))
model1.add(Dense(1, 'linear'))

model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 64)                16896

 dense (Dense)               (None, 8)                 520

 dense_1 (Dense)             (None, 1)                 9

=================================================================
Total params: 17,425
Trainable params: 17,425
Non-trainable params: 0
_________________________________________________________________

In [ ]:
cp1 = ModelCheckpoint('model1/', save_best_only=True)
model1.compile(loss=MeanSquaredError(), optimizer=Adam(learning_rate=0.0001), metrics=[RootMeanSquaredError()])

In [ ]:
model1.fit(X_train1, y_train1, validation_data=(X_val1, y_val1), epochs=10, callbacks=[cp1])